name: ESLINT CONFIG

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 14
      - run: yarn install
      - run: yarn validate
