name: ESLINT CONFIG

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - run: yarn install
      - run: yarn validate
